<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<LangVersion>14</LangVersion>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="BenchmarkDotNet" />
		<PackageReference Include="ModelContextProtocol" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="../../src/Dotsider/Dotsider.csproj" />
		<ProjectReference Include="../../src/Dotsider.Core/Dotsider.Core.csproj" />
		<ProjectReference Include="../../src/Dotsider.Mcp/Dotsider.Mcp.csproj" />
	</ItemGroup>

</Project>
