<Project>
  <PropertyGroup>
    <AnalysisLevel>latest</AnalysisLevel>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <WarningsAsErrors>$(WarningsAsErrors);IDE0005;IDE0230;IDE0300;IDE0305;IDE1006;CS1574;CS1591;CS8604;CA1416;CA1816;CA1822;CA1834;CA1861;MSTEST0001;MSTEST0002;MSTEST0003;MSTEST0004;MSTEST0005;MSTEST0006;MSTEST0007;MSTEST0008;MSTEST0009;MSTEST0010;MSTEST0011;MSTEST0012;MSTEST0013;MSTEST0014;MSTEST0015;MSTEST0016;MSTEST0017;MSTEST0018;MSTEST0019;MSTEST0020;MSTEST0021;MSTEST0022;MSTEST0023;MSTEST0024;MSTEST0025;MSTEST0026;MSTEST0027;MSTEST0028;MSTEST0029;MSTEST0030;MSTEST0031;MSTEST0032;MSTEST0033;MSTEST0034;MSTEST0035;MSTEST0036;MSTEST0037;MSTEST0038;MSTEST0039;MSTEST0040;MSTEST0041;MSTEST0042;MSTEST0043;MSTEST0044;MSTEST0045;MSTEST0046;MSTEST0047;MSTEST0048;MSTEST0049;MSTEST0050;MSTEST0051;MSTEST0052;MSTEST0053;MSTEST0054;MSTEST0055;MSTEST0056;MSTEST0057;MSTEST0058;MSTEST0059;MSTEST0060;MSTEST0061;MSTEST0062;MSTEST0063;MSTEST0064;MSTEST0065;MSTEST0066;MSTEST0067;MSTEST0068;MSTEST0069;MSTEST0070;MSTEST0071;AOTSG0001;AOTSG0002;AOTSG0003;AOTSG0004;AOTSG0005</WarningsAsErrors>
  </PropertyGroup>
</Project>
