<Project>
	<Import Project="..\Directory.Build.props" />

	<PropertyGroup>
		<MSTestAnalysisMode>All</MSTestAnalysisMode>
		<MicrosoftTestingExtensionsCodeCoverageVersion>18.11.2</MicrosoftTestingExtensionsCodeCoverageVersion>
		<IncludeSharedTestSources Condition="'$(IncludeSharedTestSources)' == ''">true</IncludeSharedTestSources>
	</PropertyGroup>

	<ItemGroup Condition="'$(IncludeSharedTestSources)' == 'true'">
		<Compile Include="$(MSBuildThisFileDirectory)Shared\*.cs" Link="Shared\%(Filename)%(Extension)" />
	</ItemGroup>
</Project>
