<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>14</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Dotsider.DocGenerator</RootNamespace>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <!-- DocFX as a library -->
    <PackageReference Include="Docfx.App" />
    <!-- TraceEvent 3.2.5 references these assemblies but omits them from its custom nuspec. -->
    <PackageReference Include="Microsoft.Bcl.HashCode" PrivateAssets="all" />
    <PackageReference Include="System.IO.Hashing" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Dotsider.Core/Dotsider.Core.csproj" />
  </ItemGroup>

</Project>
